[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"


[project]
name = "pyLiveMusic"
version = "0.0.1"
description = "A python framework for creating private room for live streaming audio using webrtc."
readme = "README.md"
requires-python = ">=3.10, <=3.14.7"

license = "MIT"
license-files = ["LICENSE"]

authors = [
    { name = "Bakachii" }
]
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

dependencies = [
    "aiortc>=1.15.0",
    "httpx>=0.28.1",
    "numpy>=2.4.4,<=2.5.2"
]

[project.optional-dependencies]

mongo = [
    "pymongo>=4.17.0",
]

redis = [
    "redis>=8.1.0",
]

aiohttp = [
    "aiohttp>=3.14.3",
]

all = [
    "pyLiveMusic[mongo,redis,aiohttp]",
]

[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.package-data]
pyLiveMusic = ["_static/*.html", "_static/*.js"]


[project.urls]
Homepage = "https://github.com/Bakachii/pyLiveMusic"
Repository = "https://github.com/Bakachii/pyLiveMusic"
Issues = "https://github.com/Bakachii/pyLiveMusic/issues"